### ISSUE TITLE
Where clause doesn't work with checksum addresses

### ISSUE THREAD

**Issue by vrde** [wighawag/eip721-subgraph#6]
:wave: I was playing with your [subgraph](https://thegraph.com/explorer/subgraph/wighawag/eip721-subgraph) and I noticed that the `where` clause (both for `tokens` and `tokenContracts`) is **case sensitive**. Not sure if this is something that should be fixed on this repo or on the "The Graph" repo.

Given that the address is a number (wrapped in a string) I expected it to work in any case.

## Query using a checksum address (sad :panda_face:)

```graphql
{
  tokenContracts (where:{id: "0xDCe09254dD3592381b6A5b7a848B29890b656e01"}) {
    id
    supportsEIP721Metadata
    numTokens
  }
}
```

No results:

```json
{
  "data": {
    "tokenContracts": []
  }
}
```

## Query using a lowercase address (works!)

```graphql
{
  tokenContracts (where:{id: "0xdce09254dd3592381b6a5b7a848b29890b656e01"}) {
    id
    supportsEIP721Metadata
    numTokens
  }
}
```

I can has tokens!

```json
{
  "data": {
    "tokenContracts": [
      {
        "id": "0xdce09254dd3592381b6a5b7a848b29890b656e01",
        "numTokens": "571",
        "supportsEIP721Metadata": true
      }
    ]
  }
}
```

**Comment by wighawag** [comment]
This is how thegraph works, ID are string
So while we could use checksum address, this would fails for lower case query

**Comment by enzoferey** [comment]
Sorry for bumping these after so much time, but is there any way of storing addresses with checksum on a subgraph ? Whenever you store it as `String` via `.toHex()` or as `Bytes` both are lowercasing the address.

**Comment by wighawag** [comment]
@enzoferey yes we could add extra field for these, but the id would still need to be a string and we need to choose a format (checksum, uppercase, or lowercase)

**Comment by enzoferey** [comment]
I mean, you should be able to convert a given address to whatever format you want to use (one of the 3 you mentioned) and then I would of course expect that if I called `.toChecksumString()` then I would need to pass a checksum address to the `where` clause.

As of right now, it's an implicit `.toLowercaseString()` and that forces clients to to convert the data going in and parse the data coming out.

But this a general TheGraph thing, nothing we could do here on this library I guess.
